### ISSUE TITLE
Matching release to coming datalad 0.15 to account for `publish` move

### ISSUE THREAD

**Issue by mih** [datalad/datalad-deprecated#29]

**Comment by yarikoptic** [comment]
any objections @mih if I push 0.2.0 to pypi with some brief CHANGELOG?

**Comment by mih** [comment]
No, not at all. I am doing the same for another extension. Thx!

**Comment by yarikoptic** [comment]
https://pypi.org/project/datalad-deprecated/ still has 0.1 , so I guess it fell through... Let's ask @jwodder to `auto` it

**Comment by yarikoptic** [comment]
0.2.2 was finally fully auto-released to pypi and github
