### ISSUE TITLE
hanging during publish attempt

### ISSUE THREAD

**Issue by leej3** [datalad/datalad-deprecated#35]
#### What is the problem?
When I publish data (pushurl to the AFNI server over ssh) I often have the process hang. This is when working with https://github.com/afni/afni_ci_test_data

#### What steps will reproduce the problem?
This has happened over the last few versions of Datalad. An example of a publish command would be:

```
datalad publish --transfer-data=all --to=afni_ci_test_data
```

If I interrupt the process (I have left it for a VERY long time sometimes) I often get an error like:

```
ERROR:
Interrupted by user while doing magic: KeyboardInterrupt() [threading.py:_wait_for_tstate_lock:1060]


^CException ignored in: <function Git.AutoInterrupt.__del__ at 0x7f5936f1fb90>
Traceback (most recent call last):
  File "/home/rodgersleejg/miniconda3/envs/datalad/lib/python3.7/site-packages/git/cmd.py", line 356, in __del__
    proc.stderr.close()
KeyboardInterrupt
(afni_dev) rodgersleejg@curium:/data/rodgersleejg/afni/tests/afni_ci_test_data$ datalad publish --transfer-data=all --to=afni_ci_test_data
[INFO   ] Publishing <Dataset path=/data/rodgersleejg/afni/tests/afni_ci_test_data> data to afni_ci_test_data
[INFO   ] Publishing <Dataset path=/data/rodgersleejg/afni/tests/afni_ci_test_data> to afni_ci_test_data
Pushing afni_ci_test_data (writing objects): 100%|█| 3.54k/3.54k [00:00<00:00, 116k ob
ERROR:
Interrupted by user while doing magic: KeyboardInterrupt() [threading.py:_wait_for_tstate_lock:1060]
```

This sometime resolves on subsequent attempts at publishing. Sometimes it seems more resistant. I have had a look at the perms in the repo on the server. It seems that the only file not globally readable/executable is the annex lock file. Perhaps that is meant to be the case (certainly makes sense to me that this would be the case). If I alter the permissions it usually stops the hanging behavior though...

```
find /fraid/pub/dist/data/afni_ci_test_data -type d  ! -perm -o=x -exec chmod o+x {} \;; find /fraid/pub/dist/data/afni_ci_test_data -type f  ! -perm -o=r -exec chmod o+r {} \;
```

**Comment by yarikoptic** [comment]
@leej3 if issue still persists, try `datalad push` instead although I think it has nothing to do with `publish` vs `push` but rather Runner implementation which I think was redone since then and now was redone again for 0.15.0.  Please reopen if issue still persists.
