### ISSUE TITLE
Is release (upload to pypi) coming? ;-)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-deprecated#4]
Is it contingent on datalad (core) release?

asking for a friend (datalad-extensions)

**Comment by mih** [comment]
No, we do not have to wait for a datalad-core release.

I wanted to get the ls() transition done first (~today).

But this morning I also had the idea that this extension might be a good candidate for auto-releases. There is no real development going on, hence the commits themselves should be straightforward documentation of progress.

**Comment by mih** [comment]
README needs an update before the release!

**Comment by mih** [comment]
All updates made, docs registered. 0.1 is on pypi.
