### ISSUE TITLE
Auto-mate releases

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-deprecated#53]
pretty much duplicating what we do in `datalad` and not bothering with `semver-` prefix for labels for now.

edit: FTR -- I would expect no other libraries to depend on datalad-deprecated functionality.  If there are such, we should consider moving that functionality in a dedicated extension.  With that, I think we could easily use semver "properly" here, and thus do increase MAJOR whenever we do remove (or break API for) some functionality, MINOR when adding new, and PATCH when fixing.  I will use labels accordingly now across previously merged PRs

**Comment by jwodder** [comment]
@yarikoptic By "what we do in `datalad`", do you mean that you want [the CHANGELOG version-checking](https://github.com/datalad/datalad/blob/b79037d62bd7eefcbf7a77d208817b0c40f80f2c/.github/workflows/release.yml#L38-L58) included?

**Comment by yarikoptic** [comment]
oh, I forgot about that extra complications. no need -- just pretty much a typical `auto` setup with `released` plugin added -- I really like that one. So I guess closer to what we have for dandi-cli.
